#!/bin/sh

DEV_DIR=/opt/dev_64_swat
PROJ_NAME=dsl2

echo "CPLUS_INCLUDE_PATH : " $CPLUS_INCLUDE_PATH
CPLUS_INCLUDE_PATH=$DEV_DIR/BOOST/include:$DEV_DIR/$PROJ_NAME/include:$DEV_DIR/gtest/include
echo "CPLUS_INCLUDE_PATH : " $CPLUS_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
